/**
 * Conversation mocks.
 *
 * NOTE: The YapShop conversations API does not yet expose a messages endpoint.
 * We're designing ahead of the backend: `messages` is embedded on the
 * Conversation type here for v1. When the messages endpoint lands, the service
 * will fetch them separately (and likely paginate), but the consuming
 * component shape (Message[]) will not change.
 */
export type ConversationStatus = "active" | "ended"

export type HandoffStatus =
  | "none"
  | "requested"
  | "active"
  | "resolved"
  | "cancelled"
  | "pending"

export type MessageSender = "customer" | "ai" | "staff" | "system"

export interface Message {
  id: string
  sender: MessageSender
  body: string
  /** Display string like "10:42" — not ISO. */
  timestamp: string
  /** Only when sender === "staff". */
  staff_name?: string
  /** Only when sender === "system"; iconography hint (we map this to an icon ourselves). */
  icon?: string
}

export interface Conversation {
  id: string
  customer_id: string
  customer_name: string
  customer_whatsapp: string
  customer_initials: string
  customer_color: string
  status: ConversationStatus
  ai_enabled: boolean
  handoff_status: HandoffStatus
  handoff_reason?: string
  handoff_requested_at?: string
  assigned_staff_id?: string
  assigned_staff_name?: string
  started_at: string
  last_message_at: string
  last_message_preview: string
  messages: Message[]
}

export type ConversationTag =
  | { kind: "attention"; label: "Needs attention" }
  | { kind: "ai"; label: "AI" }
  | { kind: "staff"; label: string }
  | { kind: "ended"; label: "Ended" }

export function getConversationTag(c: Conversation): ConversationTag {
  if (c.status === "ended") return { kind: "ended", label: "Ended" }
  if (c.handoff_status === "requested") return { kind: "attention", label: "Needs attention" }
  if (c.handoff_status === "active" && c.assigned_staff_name) {
    return { kind: "staff", label: c.assigned_staff_name }
  }
  return { kind: "ai", label: "AI" }
}

const ago = (amount: number, unit: "m" | "h" | "d"): string => {
  const ms =
    unit === "m" ? amount * 60_000 : unit === "h" ? amount * 3_600_000 : amount * 86_400_000
  return new Date(Date.now() - ms).toISOString()
}

const STAFF = ["Adaeze", "Tunde", "Sarah", "Femi"] as const

export const MOCK_CONVERSATIONS: Conversation[] = [
  // ---------- 6 named entries ----------
  {
    id: "conv-emperor-001",
    customer_id: "cust-emperor",
    customer_name: "Emperor",
    customer_whatsapp: "+234 803 124 8841",
    customer_initials: "EM",
    customer_color: "#7C2D5E",
    status: "active",
    ai_enabled: true,
    handoff_status: "requested",
    handoff_reason: "Customer wants additional product photos that the AI cannot retrieve.",
    handoff_requested_at: ago(2, "m"),
    started_at: ago(10, "m"),
    last_message_at: ago(2, "m"),
    last_message_preview: "Customer is waiting for product photos — AI escalated",
    messages: [
      { id: "m1", sender: "customer", body: "Hi, do you have Ankara dresses?", timestamp: "10:42" },
      {
        id: "m2",
        sender: "ai",
        body: "Hello! Yes, we have several Ankara dresses. Our Ankara Midi Dress is ₦12,500 and comes in three prints. Want me to share photos?",
        timestamp: "10:42",
      },
      { id: "m3", sender: "customer", body: "Yes please. Do you have size 12?", timestamp: "10:43" },
      {
        id: "m4",
        sender: "ai",
        body: "Size 12 is available in red and blue. Here's a preview of the red one.",
        timestamp: "10:43",
      },
      {
        id: "m5",
        sender: "customer",
        body: "Can I get pictures from different angles? Front and back?",
        timestamp: "10:45",
      },
      {
        id: "m6",
        sender: "system",
        body: "AI requested handoff to a human",
        timestamp: "10:45",
        icon: "arrow-right",
      },
      {
        id: "m7",
        sender: "ai",
        body: "I'll connect you with someone who can share more photos. One moment.",
        timestamp: "10:45",
      },
    ],
  },
  {
    id: "conv-ada-001",
    customer_id: "cust-ada",
    customer_name: "Ada Obi",
    customer_whatsapp: "+234 802 551 0922",
    customer_initials: "AO",
    customer_color: "#1F4D7A",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(45, "m"),
    last_message_at: ago(15, "m"),
    last_message_preview: "Yes I'll take the senator kaftan in navy, size large",
    messages: [
      { id: "m1", sender: "customer", body: "Do you have the senator kaftan still?", timestamp: "12:10" },
      {
        id: "m2",
        sender: "ai",
        body: "Yes! Senator Kaftan is ₦18,000. Available in navy, charcoal, and cream. Which would you like?",
        timestamp: "12:11",
      },
      { id: "m3", sender: "customer", body: "Navy. Size?", timestamp: "12:12" },
      { id: "m4", sender: "ai", body: "We have M, L, and XL in navy. Which size suits you?", timestamp: "12:12" },
      {
        id: "m5",
        sender: "customer",
        body: "Yes I'll take the senator kaftan in navy, size large",
        timestamp: "12:55",
      },
    ],
  },
  {
    id: "conv-tunde-001",
    customer_id: "cust-tunde",
    customer_name: "Tunde B.",
    customer_whatsapp: "+234 814 220 4571",
    customer_initials: "TB",
    customer_color: "#5C3B7E",
    status: "active",
    ai_enabled: false,
    handoff_status: "active",
    handoff_requested_at: ago(2, "h"),
    assigned_staff_id: "staff-adaeze",
    assigned_staff_name: "Adaeze",
    started_at: ago(3, "h"),
    last_message_at: ago(1, "h"),
    last_message_preview: "Perfect, send me the account details please",
    messages: [
      { id: "m1", sender: "customer", body: "I want to order the lace gown, two pieces", timestamp: "09:14" },
      { id: "m2", sender: "ai", body: "Great choice! Lace Gown is ₦25,000. Two pieces = ₦50,000.", timestamp: "09:14" },
      {
        id: "m3",
        sender: "customer",
        body: "Can I pay on delivery? Also want to add the brocade agbada",
        timestamp: "09:20",
      },
      {
        id: "m4",
        sender: "system",
        body: "AI requested handoff to a human",
        timestamp: "09:22",
        icon: "arrow-right",
      },
      {
        id: "m5",
        sender: "staff",
        staff_name: "Adaeze",
        body: "Hi Tunde, Adaeze here. Pay on delivery is ₦5k extra for that amount. Bank transfer is easier — total ₦96,200.",
        timestamp: "09:25",
      },
      { id: "m6", sender: "customer", body: "Perfect, send me the account details please", timestamp: "11:10" },
    ],
  },
  {
    id: "conv-chioma-001",
    customer_id: "cust-chioma",
    customer_name: "Chioma N.",
    customer_whatsapp: "+234 706 992 1140",
    customer_initials: "CN",
    customer_color: "#2A6E54",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(4, "h"),
    last_message_at: ago(3, "h"),
    last_message_preview: "What sizes do you have for the gele?",
    messages: [
      { id: "m1", sender: "customer", body: "Hello, I saw your gele post on IG", timestamp: "08:30" },
      { id: "m2", sender: "ai", body: "Hi! Glad you stopped by. Which gele are you interested in?", timestamp: "08:31" },
      { id: "m3", sender: "customer", body: "The teal one with sequins", timestamp: "08:31" },
      {
        id: "m4",
        sender: "ai",
        body: "Sequin Gele Headwrap is ₦4,500. Comes pre-shaped or flat.",
        timestamp: "08:32",
      },
      { id: "m5", sender: "customer", body: "What sizes do you have for the gele?", timestamp: "08:40" },
    ],
  },
  {
    id: "conv-musa-001",
    customer_id: "cust-musa",
    customer_name: "Musa K.",
    customer_whatsapp: "+234 815 008 3306",
    customer_initials: "MK",
    customer_color: "#7C2D5E",
    status: "ended",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(1, "d"),
    last_message_at: ago(1, "d"),
    last_message_preview: "Thanks, I'll think about it",
    messages: [
      { id: "m1", sender: "customer", body: "How much is the native cap?", timestamp: "14:02" },
      { id: "m2", sender: "ai", body: "Native Cap is ₦7,400. Available in black, white, and red.", timestamp: "14:02" },
      { id: "m3", sender: "customer", body: "Hmm, can you do ₦6k?", timestamp: "14:05" },
      { id: "m4", sender: "ai", body: "Our prices are fixed. Quality is guaranteed.", timestamp: "14:05" },
      { id: "m5", sender: "customer", body: "Thanks, I'll think about it", timestamp: "14:06" },
    ],
  },
  {
    id: "conv-ifeoma-001",
    customer_id: "cust-ifeoma",
    customer_name: "Ifeoma O.",
    customer_whatsapp: "+234 803 478 1290",
    customer_initials: "IO",
    customer_color: "#5C3B7E",
    status: "ended",
    ai_enabled: true,
    handoff_status: "resolved",
    started_at: ago(2, "d"),
    last_message_at: ago(2, "d"),
    last_message_preview: "Order received, thank you!",
    messages: [
      { id: "m1", sender: "customer", body: "Hi, has my order shipped?", timestamp: "10:00" },
      { id: "m2", sender: "ai", body: "Let me check. Your order #ORD-2836 shipped yesterday — DHL tracking 4112-9981.", timestamp: "10:00" },
      { id: "m3", sender: "customer", body: "When should it arrive?", timestamp: "10:01" },
      { id: "m4", sender: "ai", body: "ETA is 2–3 working days to Port Harcourt.", timestamp: "10:01" },
      { id: "m5", sender: "customer", body: "Order received, thank you!", timestamp: "16:42" },
    ],
  },

  // ---------- 24 generated entries ----------
  {
    id: "conv-gen-002",
    customer_id: "cust-gen-002",
    customer_name: "Adaobi Eze",
    customer_whatsapp: "+234 803 211 4456",
    customer_initials: "AE",
    customer_color: "#1F4D7A",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(20, "m"),
    last_message_at: ago(5, "m"),
    last_message_preview: "Beautiful! I'll take it",
    messages: [
      { id: "m1", sender: "customer", body: "Do you ship to Lagos?", timestamp: "13:20" },
      { id: "m2", sender: "ai", body: "Yes — Lagos shipping is ₦1,500 and arrives same day if ordered before noon.", timestamp: "13:20" },
      { id: "m3", sender: "customer", body: "Beautiful! I'll take it", timestamp: "13:35" },
    ],
  },
  {
    id: "conv-gen-003",
    customer_id: "cust-gen-003",
    customer_name: "Tunde Adeyemi",
    customer_whatsapp: "+234 814 776 2210",
    customer_initials: "TA",
    customer_color: "#2A6E54",
    status: "active",
    ai_enabled: true,
    handoff_status: "requested",
    handoff_reason: "Customer asking about bulk-order pricing not in the catalog.",
    handoff_requested_at: ago(8, "m"),
    started_at: ago(30, "m"),
    last_message_at: ago(8, "m"),
    last_message_preview: "I need 50 pieces for a wedding — what's the discount?",
    messages: [
      { id: "m1", sender: "customer", body: "Hello", timestamp: "12:00" },
      { id: "m2", sender: "ai", body: "Hi! How can I help?", timestamp: "12:00" },
      { id: "m3", sender: "customer", body: "I need 50 pieces for a wedding — what's the discount?", timestamp: "12:22" },
      { id: "m4", sender: "system", body: "AI requested handoff to a human", timestamp: "12:22", icon: "arrow-right" },
    ],
  },
  {
    id: "conv-gen-004",
    customer_id: "cust-gen-004",
    customer_name: "Funke Okonkwo",
    customer_whatsapp: "+234 706 433 1290",
    customer_initials: "FO",
    customer_color: "#5C3B7E",
    status: "active",
    ai_enabled: false,
    handoff_status: "active",
    handoff_requested_at: ago(40, "m"),
    assigned_staff_id: "staff-tunde",
    assigned_staff_name: "Tunde",
    started_at: ago(2, "h"),
    last_message_at: ago(25, "m"),
    last_message_preview: "Tunde, do you have it in size 14?",
    messages: [
      { id: "m1", sender: "customer", body: "Hi, the sequin evening dress — does it come in size 14?", timestamp: "11:00" },
      { id: "m2", sender: "ai", body: "Sequin Evening Dress runs S–XL. Size 14 corresponds to L.", timestamp: "11:00" },
      { id: "m3", sender: "customer", body: "I really need exact UK size 14 — can someone confirm measurements?", timestamp: "11:15" },
      { id: "m4", sender: "system", body: "AI requested handoff to a human", timestamp: "11:18", icon: "arrow-right" },
      { id: "m5", sender: "staff", staff_name: "Tunde", body: "Hi Funke — Tunde here. Bust 38, waist 32, length 56in. That's UK 14.", timestamp: "11:30" },
      { id: "m6", sender: "customer", body: "Tunde, do you have it in size 14?", timestamp: "12:30" },
    ],
  },
  {
    id: "conv-gen-005",
    customer_id: "cust-gen-005",
    customer_name: "Chidi Nwankwo",
    customer_whatsapp: "+234 815 990 4521",
    customer_initials: "CN",
    customer_color: "#5C3B7E",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(50, "m"),
    last_message_at: ago(20, "m"),
    last_message_preview: "Okay, I'll pay tomorrow",
    messages: [
      { id: "m1", sender: "customer", body: "How long do you hold a reservation?", timestamp: "12:10" },
      { id: "m2", sender: "ai", body: "We hold orders for 24 hours pending payment.", timestamp: "12:10" },
      { id: "m3", sender: "customer", body: "Okay, I'll pay tomorrow", timestamp: "12:40" },
    ],
  },
  {
    id: "conv-gen-006",
    customer_id: "cust-gen-006",
    customer_name: "Bisi Ade",
    customer_whatsapp: "+234 803 887 3344",
    customer_initials: "BA",
    customer_color: "#7C2D5E",
    status: "ended",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(1, "d"),
    last_message_at: ago(1, "d"),
    last_message_preview: "Got it, thanks",
    messages: [
      { id: "m1", sender: "customer", body: "Is the adire boubou loose-fit?", timestamp: "09:00" },
      { id: "m2", sender: "ai", body: "Yes — Adire Boubou is intentionally oversized. Free size fits 8–18.", timestamp: "09:00" },
      { id: "m3", sender: "customer", body: "Got it, thanks", timestamp: "09:02" },
    ],
  },
  {
    id: "conv-gen-007",
    customer_id: "cust-gen-007",
    customer_name: "Femi Bakare",
    customer_whatsapp: "+234 906 122 7768",
    customer_initials: "FB",
    customer_color: "#3A3D44",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(1, "h"),
    last_message_at: ago(35, "m"),
    last_message_preview: "Sent! Send confirmation when received",
    messages: [
      { id: "m1", sender: "customer", body: "Bank details?", timestamp: "11:55" },
      { id: "m2", sender: "ai", body: "GTBank 0123456789 — YapShop Ltd.", timestamp: "11:55" },
      { id: "m3", sender: "customer", body: "Sent! Send confirmation when received", timestamp: "12:25" },
    ],
  },
  {
    id: "conv-gen-008",
    customer_id: "cust-gen-008",
    customer_name: "Yetunde Lawal",
    customer_whatsapp: "+234 802 445 1190",
    customer_initials: "YL",
    customer_color: "#1F4D7A",
    status: "active",
    ai_enabled: false,
    handoff_status: "active",
    assigned_staff_id: "staff-sarah",
    assigned_staff_name: "Sarah",
    handoff_requested_at: ago(50, "m"),
    started_at: ago(2, "h"),
    last_message_at: ago(15, "m"),
    last_message_preview: "Sarah, can you DM me the swatch photos?",
    messages: [
      { id: "m1", sender: "customer", body: "I need the bridal lace fabric — can I see swatches?", timestamp: "11:00" },
      { id: "m2", sender: "ai", body: "We have ivory, blush, and gold. Would you like a brochure?", timestamp: "11:00" },
      { id: "m3", sender: "customer", body: "I want actual swatches in person", timestamp: "11:10" },
      { id: "m4", sender: "system", body: "AI requested handoff to a human", timestamp: "11:12", icon: "arrow-right" },
      { id: "m5", sender: "staff", staff_name: "Sarah", body: "Hi Yetunde — Sarah from sales. I can post swatches today via courier.", timestamp: "11:20" },
      { id: "m6", sender: "customer", body: "Sarah, can you DM me the swatch photos?", timestamp: "12:45" },
    ],
  },
  {
    id: "conv-gen-009",
    customer_id: "cust-gen-009",
    customer_name: "Kunle Ojo",
    customer_whatsapp: "+234 814 552 3387",
    customer_initials: "KO",
    customer_color: "#7A4419",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(2, "h"),
    last_message_at: ago(50, "m"),
    last_message_preview: "Ordered. Confirmation number?",
    messages: [
      { id: "m1", sender: "customer", body: "Aso Oke cap please", timestamp: "11:00" },
      { id: "m2", sender: "ai", body: "Aso Oke Cap is ₦5,500. Color preference?", timestamp: "11:00" },
      { id: "m3", sender: "customer", body: "Cream", timestamp: "11:05" },
      { id: "m4", sender: "ai", body: "Cream is in stock. Confirm address to proceed.", timestamp: "11:06" },
      { id: "m5", sender: "customer", body: "Ordered. Confirmation number?", timestamp: "12:10" },
    ],
  },
  {
    id: "conv-gen-010",
    customer_id: "cust-gen-010",
    customer_name: "Ngozi Akpan",
    customer_whatsapp: "+234 706 334 6612",
    customer_initials: "NA",
    customer_color: "#3A3D44",
    status: "ended",
    ai_enabled: true,
    handoff_status: "cancelled",
    started_at: ago(3, "d"),
    last_message_at: ago(3, "d"),
    last_message_preview: "Never mind, found it cheaper",
    messages: [
      { id: "m1", sender: "customer", body: "Iro and buba set, ₦15k?", timestamp: "10:00" },
      { id: "m2", sender: "ai", body: "Iro and Buba Set is ₦18,000.", timestamp: "10:00" },
      { id: "m3", sender: "customer", body: "Never mind, found it cheaper", timestamp: "10:02" },
    ],
  },
  {
    id: "conv-gen-011",
    customer_id: "cust-gen-011",
    customer_name: "Olumide Smith",
    customer_whatsapp: "+234 803 991 4456",
    customer_initials: "OS",
    customer_color: "#5C3B7E",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(5, "h"),
    last_message_at: ago(2, "h"),
    last_message_preview: "Send the lookbook please",
    messages: [
      { id: "m1", sender: "customer", body: "Do you have a lookbook?", timestamp: "08:30" },
      { id: "m2", sender: "ai", body: "Yes — our 2026 collection PDF is 32 pages. I can drop it here.", timestamp: "08:30" },
      { id: "m3", sender: "customer", body: "Send the lookbook please", timestamp: "11:30" },
    ],
  },
  {
    id: "conv-gen-012",
    customer_id: "cust-gen-012",
    customer_name: "Tope Akin",
    customer_whatsapp: "+234 815 663 7790",
    customer_initials: "TA",
    customer_color: "#5C3B7E",
    status: "active",
    ai_enabled: true,
    handoff_status: "resolved",
    started_at: ago(7, "h"),
    last_message_at: ago(3, "h"),
    last_message_preview: "Perfect, sorted",
    messages: [
      { id: "m1", sender: "customer", body: "Wrong color delivered", timestamp: "07:00" },
      { id: "m2", sender: "system", body: "AI requested handoff to a human", timestamp: "07:01", icon: "arrow-right" },
      { id: "m3", sender: "staff", staff_name: "Sarah", body: "So sorry — I'll send the right one tomorrow. Send the wrong one back via dispatch.", timestamp: "07:30" },
      { id: "m4", sender: "system", body: "Staff resumed AI mode", timestamp: "08:00", icon: "check" },
      { id: "m5", sender: "customer", body: "Perfect, sorted", timestamp: "10:30" },
    ],
  },
  {
    id: "conv-gen-013",
    customer_id: "cust-gen-013",
    customer_name: "Sade Davis",
    customer_whatsapp: "+234 902 887 4422",
    customer_initials: "SD",
    customer_color: "#2A6E54",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(35, "m"),
    last_message_at: ago(30, "m"),
    last_message_preview: "Thanks, will pay shortly",
    messages: [
      { id: "m1", sender: "customer", body: "How much is the gele headwrap?", timestamp: "13:00" },
      { id: "m2", sender: "ai", body: "₦4,500.", timestamp: "13:00" },
      { id: "m3", sender: "customer", body: "Thanks, will pay shortly", timestamp: "13:05" },
    ],
  },
  {
    id: "conv-gen-014",
    customer_id: "cust-gen-014",
    customer_name: "Bayo Falade",
    customer_whatsapp: "+234 814 998 1123",
    customer_initials: "BF",
    customer_color: "#5C3B7E",
    status: "ended",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(4, "d"),
    last_message_at: ago(4, "d"),
    last_message_preview: "Received, thanks",
    messages: [
      { id: "m1", sender: "customer", body: "Brocade agbada delivered today, thanks", timestamp: "16:00" },
      { id: "m2", sender: "ai", body: "Thanks for confirming! Hope it fits well.", timestamp: "16:00" },
      { id: "m3", sender: "customer", body: "Received, thanks", timestamp: "16:01" },
    ],
  },
  {
    id: "conv-gen-015",
    customer_id: "cust-gen-015",
    customer_name: "Ifeanyi Obi",
    customer_whatsapp: "+234 803 446 8890",
    customer_initials: "IO",
    customer_color: "#7A4419",
    status: "active",
    ai_enabled: true,
    handoff_status: "requested",
    handoff_reason: "Customer requesting last-minute tailoring; AI cannot promise turnaround.",
    handoff_requested_at: ago(12, "m"),
    started_at: ago(1, "h"),
    last_message_at: ago(12, "m"),
    last_message_preview: "Can it be ready by Saturday?",
    messages: [
      { id: "m1", sender: "customer", body: "I need the boys senator set urgently", timestamp: "12:00" },
      { id: "m2", sender: "ai", body: "Boys Senator Set is ₦19,000, available now.", timestamp: "12:00" },
      { id: "m3", sender: "customer", body: "Can it be ready by Saturday?", timestamp: "12:48" },
      { id: "m4", sender: "system", body: "AI requested handoff to a human", timestamp: "12:48", icon: "arrow-right" },
    ],
  },
  {
    id: "conv-gen-016",
    customer_id: "cust-gen-016",
    customer_name: "Halima Aliyu",
    customer_whatsapp: "+234 906 552 3344",
    customer_initials: "HA",
    customer_color: "#2A6E54",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(2, "h"),
    last_message_at: ago(1, "h"),
    last_message_preview: "Got it",
    messages: [
      { id: "m1", sender: "customer", body: "Do you have girls dresses size 6?", timestamp: "10:30" },
      { id: "m2", sender: "ai", body: "Girls Ankara Dress is ₦8,500 in sizes 4–12.", timestamp: "10:30" },
      { id: "m3", sender: "customer", body: "Got it", timestamp: "11:30" },
    ],
  },
  {
    id: "conv-gen-017",
    customer_id: "cust-gen-017",
    customer_name: "Mary James",
    customer_whatsapp: "+234 815 117 4490",
    customer_initials: "MJ",
    customer_color: "#1F4D7A",
    status: "ended",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(5, "d"),
    last_message_at: ago(5, "d"),
    last_message_preview: "Will order later",
    messages: [
      { id: "m1", sender: "customer", body: "Aso Ebi for 8 ladies — bulk price?", timestamp: "09:00" },
      { id: "m2", sender: "ai", body: "Lace Aso Ebi Dress is ₦28,500. 5%+ off for 6 pieces or more.", timestamp: "09:00" },
      { id: "m3", sender: "customer", body: "Will order later", timestamp: "09:30" },
    ],
  },
  {
    id: "conv-gen-018",
    customer_id: "cust-gen-018",
    customer_name: "Peter Okeke",
    customer_whatsapp: "+234 706 998 5562",
    customer_initials: "PO",
    customer_color: "#2A6E54",
    status: "active",
    ai_enabled: false,
    handoff_status: "active",
    handoff_requested_at: ago(20, "m"),
    assigned_staff_id: "staff-femi",
    assigned_staff_name: "Femi",
    started_at: ago(45, "m"),
    last_message_at: ago(10, "m"),
    last_message_preview: "Femi, please confirm dispatch by 4pm",
    messages: [
      { id: "m1", sender: "customer", body: "Same-day delivery to Surulere?", timestamp: "12:00" },
      { id: "m2", sender: "ai", body: "Yes, if order is in by 1pm. ₦1,500 fee.", timestamp: "12:00" },
      { id: "m3", sender: "customer", body: "Need it before 5pm — guarantee?", timestamp: "12:15" },
      { id: "m4", sender: "system", body: "AI requested handoff to a human", timestamp: "12:17", icon: "arrow-right" },
      { id: "m5", sender: "staff", staff_name: "Femi", body: "Femi here — I'll personally dispatch by 2pm.", timestamp: "12:25" },
      { id: "m6", sender: "customer", body: "Femi, please confirm dispatch by 4pm", timestamp: "12:35" },
    ],
  },
  {
    id: "conv-gen-019",
    customer_id: "cust-gen-019",
    customer_name: "John Bello",
    customer_whatsapp: "+234 803 223 7780",
    customer_initials: "JB",
    customer_color: "#1F4D7A",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(3, "h"),
    last_message_at: ago(1, "h"),
    last_message_preview: "Thanks, will order tomorrow",
    messages: [
      { id: "m1", sender: "customer", body: "Beaded necklace — handmade?", timestamp: "10:00" },
      { id: "m2", sender: "ai", body: "Yes, hand-strung in Aba. Each piece slightly different.", timestamp: "10:00" },
      { id: "m3", sender: "customer", body: "Thanks, will order tomorrow", timestamp: "12:00" },
    ],
  },
  {
    id: "conv-gen-020",
    customer_id: "cust-gen-020",
    customer_name: "Hauwa Ibrahim",
    customer_whatsapp: "+234 902 334 9981",
    customer_initials: "HI",
    customer_color: "#1F4D7A",
    status: "active",
    ai_enabled: true,
    handoff_status: "resolved",
    started_at: ago(5, "h"),
    last_message_at: ago(2, "h"),
    last_message_preview: "Sorted — thanks",
    messages: [
      { id: "m1", sender: "customer", body: "Bridal lace ordered yesterday — wrong package received", timestamp: "08:00" },
      { id: "m2", sender: "system", body: "AI requested handoff to a human", timestamp: "08:01", icon: "arrow-right" },
      { id: "m3", sender: "staff", staff_name: "Adaeze", body: "So sorry Hauwa — will replace by EOD.", timestamp: "08:15" },
      { id: "m4", sender: "system", body: "Staff resumed AI mode", timestamp: "10:00", icon: "check" },
      { id: "m5", sender: "customer", body: "Sorted — thanks", timestamp: "11:00" },
    ],
  },
  {
    id: "conv-gen-021",
    customer_id: "cust-gen-021",
    customer_name: "Esther Adeola",
    customer_whatsapp: "+234 814 778 2210",
    customer_initials: "EA",
    customer_color: "#2A6E54",
    status: "ended",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(6, "d"),
    last_message_at: ago(6, "d"),
    last_message_preview: "Cool, thanks",
    messages: [
      { id: "m1", sender: "customer", body: "Bubu dress in cobalt?", timestamp: "10:00" },
      { id: "m2", sender: "ai", body: "Bubu Dress is ₦11,000. Cobalt is in stock.", timestamp: "10:00" },
      { id: "m3", sender: "customer", body: "Cool, thanks", timestamp: "10:01" },
    ],
  },
  {
    id: "conv-gen-022",
    customer_id: "cust-gen-022",
    customer_name: "David Adebayo",
    customer_whatsapp: "+234 803 663 8870",
    customer_initials: "DA",
    customer_color: "#1F4D7A",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(4, "h"),
    last_message_at: ago(2, "h"),
    last_message_preview: "Will confirm tomorrow",
    messages: [
      { id: "m1", sender: "customer", body: "Two bridal lace pieces, ₦150k cash on delivery?", timestamp: "08:00" },
      { id: "m2", sender: "ai", body: "Sorry — COD over ₦100k requires 50% deposit.", timestamp: "08:00" },
      { id: "m3", sender: "customer", body: "Will confirm tomorrow", timestamp: "11:00" },
    ],
  },
  {
    id: "conv-gen-023",
    customer_id: "cust-gen-023",
    customer_name: "Grace Olatunji",
    customer_whatsapp: "+234 906 445 7790",
    customer_initials: "GO",
    customer_color: "#1F4D7A",
    status: "ended",
    ai_enabled: true,
    handoff_status: "cancelled",
    started_at: ago(7, "d"),
    last_message_at: ago(7, "d"),
    last_message_preview: "Cancelling",
    messages: [
      { id: "m1", sender: "customer", body: "Coral beads set — can I see all colors?", timestamp: "09:00" },
      { id: "m2", sender: "ai", body: "Available in coral, ivory, and turquoise.", timestamp: "09:00" },
      { id: "m3", sender: "customer", body: "Cancelling", timestamp: "09:02" },
    ],
  },
  {
    id: "conv-gen-024",
    customer_id: "cust-gen-024",
    customer_name: "Ahmed Musa",
    customer_whatsapp: "+234 815 998 1145",
    customer_initials: "AM",
    customer_color: "#5C3B7E",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(6, "h"),
    last_message_at: ago(4, "h"),
    last_message_preview: "Got it, thanks",
    messages: [
      { id: "m1", sender: "customer", body: "Leather sandals size 44?", timestamp: "08:00" },
      { id: "m2", sender: "ai", body: "Leather Sandal is ₦18,500. Size 44 in brown and black.", timestamp: "08:00" },
      { id: "m3", sender: "customer", body: "Got it, thanks", timestamp: "10:00" },
    ],
  },
  {
    id: "conv-gen-025",
    customer_id: "cust-gen-025",
    customer_name: "Stella Eke",
    customer_whatsapp: "+234 706 552 3387",
    customer_initials: "SE",
    customer_color: "#3A3D44",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(2, "h"),
    last_message_at: ago(1, "h"),
    last_message_preview: "Ordered. Awaiting confirmation",
    messages: [
      { id: "m1", sender: "customer", body: "Ankara pants — slim fit?", timestamp: "10:30" },
      { id: "m2", sender: "ai", body: "Stretch Ankara Pants are slim-fit. ₦9,000.", timestamp: "10:30" },
      { id: "m3", sender: "customer", body: "Ordered. Awaiting confirmation", timestamp: "11:30" },
    ],
  },
  {
    id: "conv-gen-026",
    customer_id: "cust-gen-026",
    customer_name: "Linda Etim",
    customer_whatsapp: "+234 803 559 1188",
    customer_initials: "LE",
    customer_color: "#7C2D5E",
    status: "ended",
    ai_enabled: true,
    handoff_status: "resolved",
    started_at: ago(2, "d"),
    last_message_at: ago(2, "d"),
    last_message_preview: "All set, thanks team",
    messages: [
      { id: "m1", sender: "customer", body: "Wrong size dispatched", timestamp: "09:00" },
      { id: "m2", sender: "system", body: "AI requested handoff to a human", timestamp: "09:01", icon: "arrow-right" },
      { id: "m3", sender: "staff", staff_name: "Sarah", body: "Apologies — will swap by tomorrow.", timestamp: "09:10" },
      { id: "m4", sender: "customer", body: "All set, thanks team", timestamp: "16:00" },
    ],
  },
  {
    id: "conv-gen-027",
    customer_id: "cust-gen-027",
    customer_name: "Mike Anjorin",
    customer_whatsapp: "+234 814 002 9943",
    customer_initials: "MA",
    customer_color: "#7A4419",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(1, "h"),
    last_message_at: ago(45, "m"),
    last_message_preview: "Cool, send the link",
    messages: [
      { id: "m1", sender: "customer", body: "Do you have an Instagram catalog?", timestamp: "12:00" },
      { id: "m2", sender: "ai", body: "Yes — @yapshop on IG.", timestamp: "12:00" },
      { id: "m3", sender: "customer", body: "Cool, send the link", timestamp: "12:15" },
    ],
  },
  {
    id: "conv-gen-028",
    customer_id: "cust-gen-028",
    customer_name: "Rita Onuoha",
    customer_whatsapp: "+234 706 117 8821",
    customer_initials: "RO",
    customer_color: "#5C3B7E",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(3, "h"),
    last_message_at: ago(2, "h"),
    last_message_preview: "Got the receipt thanks",
    messages: [
      { id: "m1", sender: "customer", body: "Sent payment for the gown", timestamp: "09:30" },
      { id: "m2", sender: "ai", body: "Confirmed. Order #ORD-2829 logged.", timestamp: "09:31" },
      { id: "m3", sender: "customer", body: "Got the receipt thanks", timestamp: "10:30" },
    ],
  },
  {
    id: "conv-gen-029",
    customer_id: "cust-gen-029",
    customer_name: "Ola Ade",
    customer_whatsapp: "+234 815 882 1190",
    customer_initials: "OA",
    customer_color: "#2A6E54",
    status: "ended",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(8, "d"),
    last_message_at: ago(8, "d"),
    last_message_preview: "K bye",
    messages: [
      { id: "m1", sender: "customer", body: "Are you a real shop?", timestamp: "13:00" },
      { id: "m2", sender: "ai", body: "Yes! YapShop is a registered Nigerian fashion business since 2022.", timestamp: "13:00" },
      { id: "m3", sender: "customer", body: "K bye", timestamp: "13:01" },
    ],
  },
  {
    id: "conv-gen-030",
    customer_id: "cust-gen-030",
    customer_name: "Zainab Bello",
    customer_whatsapp: "+234 902 776 4421",
    customer_initials: "ZB",
    customer_color: "#7C2D5E",
    status: "active",
    ai_enabled: true,
    handoff_status: "none",
    started_at: ago(50, "m"),
    last_message_at: ago(20, "m"),
    last_message_preview: "Will think and revert",
    messages: [
      { id: "m1", sender: "customer", body: "Print maxi dress — Ankara or wax?", timestamp: "12:00" },
      { id: "m2", sender: "ai", body: "Both fabrics available. Ankara feels softer, wax holds shape better.", timestamp: "12:00" },
      { id: "m3", sender: "customer", body: "Will think and revert", timestamp: "12:30" },
    ],
  },
]
