export type OrderStatus =
  | "pending"
  | "paid"
  | "shipped"
  | "delivered"
  | "cancelled"

export type PaymentStatus = "pending" | "completed" | "failed"

export interface OrderItem {
  id: string
  product_id: string
  product_name: string
  product_sku: string
  thumbnail_color: string
  initials: string
  unit_price: number
  quantity: number
  subtotal: number
}

export interface DeliveryAddress {
  full_name: string
  phone_number: string
  line: string
  city: string
  state: string
  country: string
  landmark?: string
}

export interface Order {
  id: string
  order_number: string
  customer_name: string
  customer_whatsapp: string
  status: OrderStatus
  payment_status: PaymentStatus
  payment_method?: string
  total_amount: number
  created_at: string
  items: OrderItem[]
  delivery: DeliveryAddress
}

/** Helper to render an ISO date relative to "now" at module load. */
const ago = (
  amount: number,
  unit: "m" | "h" | "d",
): string => {
  const ms =
    unit === "m" ? amount * 60_000 : unit === "h" ? amount * 3_600_000 : amount * 86_400_000
  return new Date(Date.now() - ms).toISOString()
}

/** Item factory — drop new items in quickly without re-spelling fields. */
const item = (
  id: string,
  product_id: string,
  product_name: string,
  product_sku: string,
  thumbnail_color: string,
  initials: string,
  unit_price: number,
  quantity = 1,
): OrderItem => ({
  id,
  product_id,
  product_name,
  product_sku,
  thumbnail_color,
  initials,
  unit_price,
  quantity,
  subtotal: unit_price * quantity,
})

export const MOCK_ORDERS: Order[] = [
  // -------- named entries from the spec --------
  {
    id: "ord-2841",
    order_number: "#ORD-2841",
    customer_name: "Emperor",
    customer_whatsapp: "+234 803 124 8841",
    status: "pending",
    payment_status: "pending",
    total_amount: 43500,
    created_at: ago(2, "h"),
    items: [
      item("i1", "1", "Ankara Midi Dress", "AMD-001", "#7C2D5E", "AM", 12500, 1),
      item("i2", "4", "Agbada Set", "AS-004", "#7A4419", "AS", 31000, 1),
    ],
    delivery: {
      full_name: "Emperor Eze",
      phone_number: "+234 803 124 8841",
      line: "14 Wole Soyinka Street",
      city: "Yaba",
      state: "Lagos",
      country: "Nigeria",
      landmark: "Beside Eko Hospital",
    },
  },
  {
    id: "ord-2840",
    order_number: "#ORD-2840",
    customer_name: "Ada Obi",
    customer_whatsapp: "+234 802 551 0922",
    status: "paid",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 18000,
    created_at: ago(4, "h"),
    items: [item("i3", "2", "Senator Kaftan", "SK-002", "#1F4D7A", "SK", 18000, 1)],
    delivery: {
      full_name: "Ada Obi",
      phone_number: "+234 802 551 0922",
      line: "22 Adeniyi Jones Avenue",
      city: "Ikeja",
      state: "Lagos",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2839",
    order_number: "#ORD-2839",
    customer_name: "Tunde B.",
    customer_whatsapp: "+234 814 220 4571",
    status: "shipped",
    payment_status: "completed",
    payment_method: "Bank transfer",
    total_amount: 96200,
    created_at: ago(1, "d"),
    items: [
      item("i4", "3", "Lace Gown", "LG-003", "#5C3B7E", "LG", 25000, 2),
      item("i5", "15", "Brocade Agbada", "BA-014", "#5C3B7E", "BA", 46200, 1),
    ],
    delivery: {
      full_name: "Tunde Bello",
      phone_number: "+234 814 220 4571",
      line: "9 Allen Avenue",
      city: "Ikeja",
      state: "Lagos",
      country: "Nigeria",
      landmark: "Opposite Computer Village",
    },
  },
  {
    id: "ord-2838",
    order_number: "#ORD-2838",
    customer_name: "Chioma N.",
    customer_whatsapp: "+234 706 992 1140",
    status: "delivered",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 12750,
    created_at: ago(2, "d"),
    items: [
      item("i6", "11", "Bubu Dress", "BD-010", "#2A6E54", "BD", 11000, 1),
      item("i7", "5", "Gele Headwrap", "GH-005", "#2A6E54", "GH", 1750, 1),
    ],
    delivery: {
      full_name: "Chioma Nwosu",
      phone_number: "+234 706 992 1140",
      line: "5b Bourdillon Road",
      city: "Ikoyi",
      state: "Lagos",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2837",
    order_number: "#ORD-2837",
    customer_name: "Musa K.",
    customer_whatsapp: "+234 815 008 3306",
    status: "cancelled",
    payment_status: "failed",
    total_amount: 7400,
    created_at: ago(3, "d"),
    items: [item("i8", "19", "Native Cap", "NC-018", "#7C2D5E", "NC", 7400, 1)],
    delivery: {
      full_name: "Musa Khalid",
      phone_number: "+234 815 008 3306",
      line: "PLOT 12 Wuse Zone 4",
      city: "Abuja",
      state: "FCT",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2836",
    order_number: "#ORD-2836",
    customer_name: "Ifeoma O.",
    customer_whatsapp: "+234 803 478 1290",
    status: "delivered",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 25000,
    created_at: ago(4, "d"),
    items: [item("i9", "3", "Lace Gown", "LG-003", "#5C3B7E", "LG", 25000, 1)],
    delivery: {
      full_name: "Ifeoma Okafor",
      phone_number: "+234 803 478 1290",
      line: "47 Olu Obasanjo Avenue",
      city: "Port Harcourt",
      state: "Rivers",
      country: "Nigeria",
    },
  },

  // -------- generated entries (24) --------
  {
    id: "ord-2835",
    order_number: "#ORD-2835",
    customer_name: "Adaobi Eze",
    customer_whatsapp: "+234 803 211 4456",
    status: "paid",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 15500,
    created_at: ago(5, "h"),
    items: [item("g1", "8", "Kente Wrapper", "KW-007", "#1F4D7A", "KW", 15500, 1)],
    delivery: {
      full_name: "Adaobi Eze",
      phone_number: "+234 803 211 4456",
      line: "12 Awolowo Road",
      city: "Ikoyi",
      state: "Lagos",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2834",
    order_number: "#ORD-2834",
    customer_name: "Tunde Adeyemi",
    customer_whatsapp: "+234 814 776 2210",
    status: "pending",
    payment_status: "pending",
    total_amount: 8900,
    created_at: ago(8, "h"),
    items: [item("g2", "23", "Girls Ankara Dress", "GA-022", "#2A6E54", "GA", 8500, 1), item("g2b", "5", "Gele Headwrap", "GH-005", "#2A6E54", "GH", 400, 1)],
    delivery: {
      full_name: "Tunde Adeyemi",
      phone_number: "+234 814 776 2210",
      line: "23 Opebi Road",
      city: "Ikeja",
      state: "Lagos",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2833",
    order_number: "#ORD-2833",
    customer_name: "Funke Okonkwo",
    customer_whatsapp: "+234 706 433 1290",
    status: "paid",
    payment_status: "completed",
    payment_method: "Bank transfer",
    total_amount: 35000,
    created_at: ago(12, "h"),
    items: [item("g3", "33", "Sequin Evening Dress", "SQ-032", "#5C3B7E", "SQ", 35000, 1)],
    delivery: {
      full_name: "Funke Okonkwo",
      phone_number: "+234 706 433 1290",
      line: "8 Lekki Phase 1",
      city: "Lekki",
      state: "Lagos",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2832",
    order_number: "#ORD-2832",
    customer_name: "Chidi Nwankwo",
    customer_whatsapp: "+234 815 990 4521",
    status: "shipped",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 42500,
    created_at: ago(2, "d"),
    items: [item("g4", "9", "Velvet Sequin Gown", "VG-008", "#5C3B7E", "VG", 38000, 1), item("g4b", "5", "Gele Headwrap", "GH-005", "#2A6E54", "GH", 4500, 1)],
    delivery: {
      full_name: "Chidi Nwankwo",
      phone_number: "+234 815 990 4521",
      line: "44 Aba Road",
      city: "Port Harcourt",
      state: "Rivers",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2831",
    order_number: "#ORD-2831",
    customer_name: "Bisi Ade",
    customer_whatsapp: "+234 803 887 3344",
    status: "delivered",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 9500,
    created_at: ago(5, "d"),
    items: [item("g5", "7", "Adire Boubou", "AB-006", "#7C2D5E", "AB", 9500, 1)],
    delivery: {
      full_name: "Bisi Ade",
      phone_number: "+234 803 887 3344",
      line: "10 Adeniran Ogunsanya St",
      city: "Surulere",
      state: "Lagos",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2830",
    order_number: "#ORD-2830",
    customer_name: "Femi Bakare",
    customer_whatsapp: "+234 906 122 7768",
    status: "pending",
    payment_status: "pending",
    total_amount: 12000,
    created_at: ago(1, "h"),
    items: [item("g6", "24", "Plain Slim Pants", "PS-023", "#3A3D44", "PS", 12000, 1)],
    delivery: {
      full_name: "Femi Bakare",
      phone_number: "+234 906 122 7768",
      line: "5 Independence Way",
      city: "Kaduna",
      state: "Kaduna",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2829",
    order_number: "#ORD-2829",
    customer_name: "Yetunde Lawal",
    customer_whatsapp: "+234 802 445 1190",
    status: "paid",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 67500,
    created_at: ago(6, "h"),
    items: [item("g7", "26", "Bridal Lace", "BL-025", "#1F4D7A", "BL", 67500, 1)],
    delivery: {
      full_name: "Yetunde Lawal",
      phone_number: "+234 802 445 1190",
      line: "PLOT 7 Maitama",
      city: "Abuja",
      state: "FCT",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2828",
    order_number: "#ORD-2828",
    customer_name: "Kunle Ojo",
    customer_whatsapp: "+234 814 552 3387",
    status: "pending",
    payment_status: "pending",
    total_amount: 5500,
    created_at: ago(3, "h"),
    items: [item("g8", "10", "Aso Oke Cap", "AO-009", "#7A4419", "AO", 5500, 1)],
    delivery: {
      full_name: "Kunle Ojo",
      phone_number: "+234 814 552 3387",
      line: "16 Ibadan Express",
      city: "Ibadan",
      state: "Oyo",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2827",
    order_number: "#ORD-2827",
    customer_name: "Ngozi Akpan",
    customer_whatsapp: "+234 706 334 6612",
    status: "cancelled",
    payment_status: "failed",
    total_amount: 18000,
    created_at: ago(6, "d"),
    items: [item("g9", "18", "Iro and Buba Set", "IB-017", "#3A3D44", "IB", 18000, 1)],
    delivery: {
      full_name: "Ngozi Akpan",
      phone_number: "+234 706 334 6612",
      line: "30 New Haven",
      city: "Enugu",
      state: "Enugu",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2826",
    order_number: "#ORD-2826",
    customer_name: "Olumide Smith",
    customer_whatsapp: "+234 803 991 4456",
    status: "shipped",
    payment_status: "completed",
    payment_method: "Bank transfer",
    total_amount: 108000,
    created_at: ago(3, "d"),
    items: [
      item("g10", "15", "Brocade Agbada", "BA-014", "#5C3B7E", "BA", 52000, 1),
      item("g10b", "13", "Embellished Senator", "ES-012", "#7C2D5E", "ES", 32000, 1),
      item("g10c", "4", "Agbada Set", "AS-004", "#7A4419", "AS", 24000, 1),
    ],
    delivery: {
      full_name: "Olumide Smith",
      phone_number: "+234 803 991 4456",
      line: "21 Banana Island",
      city: "Ikoyi",
      state: "Lagos",
      country: "Nigeria",
      landmark: "Gate 3",
    },
  },
  {
    id: "ord-2825",
    order_number: "#ORD-2825",
    customer_name: "Tope Akin",
    customer_whatsapp: "+234 815 663 7790",
    status: "paid",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 25000,
    created_at: ago(7, "h"),
    items: [item("g11", "3", "Lace Gown", "LG-003", "#5C3B7E", "LG", 25000, 1)],
    delivery: {
      full_name: "Tope Akin",
      phone_number: "+234 815 663 7790",
      line: "4 University Road",
      city: "Akoka",
      state: "Lagos",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2824",
    order_number: "#ORD-2824",
    customer_name: "Sade Davis",
    customer_whatsapp: "+234 902 887 4422",
    status: "pending",
    payment_status: "pending",
    total_amount: 4500,
    created_at: ago(30, "m"),
    items: [item("g12", "5", "Gele Headwrap", "GH-005", "#2A6E54", "GH", 4500, 1)],
    delivery: {
      full_name: "Sade Davis",
      phone_number: "+234 902 887 4422",
      line: "7 Bode Thomas",
      city: "Surulere",
      state: "Lagos",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2823",
    order_number: "#ORD-2823",
    customer_name: "Bayo Falade",
    customer_whatsapp: "+234 814 998 1123",
    status: "delivered",
    payment_status: "completed",
    payment_method: "Bank transfer",
    total_amount: 52000,
    created_at: ago(7, "d"),
    items: [item("g13", "15", "Brocade Agbada", "BA-014", "#5C3B7E", "BA", 52000, 1)],
    delivery: {
      full_name: "Bayo Falade",
      phone_number: "+234 814 998 1123",
      line: "5 Mokola",
      city: "Ibadan",
      state: "Oyo",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2822",
    order_number: "#ORD-2822",
    customer_name: "Ifeanyi Obi",
    customer_whatsapp: "+234 803 446 8890",
    status: "paid",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 19000,
    created_at: ago(9, "h"),
    items: [item("g14", "22", "Boys Senator Set", "BS-021", "#7A4419", "BS", 19000, 1)],
    delivery: {
      full_name: "Ifeanyi Obi",
      phone_number: "+234 803 446 8890",
      line: "12 Independence Layout",
      city: "Enugu",
      state: "Enugu",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2821",
    order_number: "#ORD-2821",
    customer_name: "Halima Aliyu",
    customer_whatsapp: "+234 906 552 3344",
    status: "pending",
    payment_status: "pending",
    total_amount: 8500,
    created_at: ago(14, "h"),
    items: [item("g15", "23", "Girls Ankara Dress", "GA-022", "#2A6E54", "GA", 8500, 1)],
    delivery: {
      full_name: "Halima Aliyu",
      phone_number: "+234 906 552 3344",
      line: "PLOT 22 Garki II",
      city: "Abuja",
      state: "FCT",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2820",
    order_number: "#ORD-2820",
    customer_name: "Mary James",
    customer_whatsapp: "+234 815 117 4490",
    status: "shipped",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 31500,
    created_at: ago(4, "d"),
    items: [
      item("g16", "14", "Lace Aso Ebi Dress", "LA-013", "#1F4D7A", "LA", 28500, 1),
      item("g16b", "5", "Gele Headwrap", "GH-005", "#2A6E54", "GH", 3000, 1),
    ],
    delivery: {
      full_name: "Mary James",
      phone_number: "+234 815 117 4490",
      line: "9 Eastern Bypass",
      city: "Owerri",
      state: "Imo",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2819",
    order_number: "#ORD-2819",
    customer_name: "Peter Okeke",
    customer_whatsapp: "+234 706 998 5562",
    status: "paid",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 14500,
    created_at: ago(11, "h"),
    items: [item("g17", "17", "Print Maxi Dress", "PM-016", "#2A6E54", "PM", 14500, 1)],
    delivery: {
      full_name: "Peter Okeke",
      phone_number: "+234 706 998 5562",
      line: "1 Trans Amadi",
      city: "Port Harcourt",
      state: "Rivers",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2818",
    order_number: "#ORD-2818",
    customer_name: "John Bello",
    customer_whatsapp: "+234 803 223 7780",
    status: "pending",
    payment_status: "pending",
    total_amount: 7800,
    created_at: ago(20, "h"),
    items: [item("g18", "20", "Beaded Necklace", "BN-019", "#1F4D7A", "BN", 7800, 1)],
    delivery: {
      full_name: "John Bello",
      phone_number: "+234 803 223 7780",
      line: "16 Awolowo Way",
      city: "Ikeja",
      state: "Lagos",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2817",
    order_number: "#ORD-2817",
    customer_name: "Hauwa Ibrahim",
    customer_whatsapp: "+234 902 334 9981",
    status: "paid",
    payment_status: "completed",
    payment_method: "Bank transfer",
    total_amount: 95000,
    created_at: ago(13, "h"),
    items: [
      item("g19", "26", "Bridal Lace", "BL-025", "#1F4D7A", "BL", 75000, 1),
      item("g19b", "8", "Kente Wrapper", "KW-007", "#1F4D7A", "KW", 20000, 1),
    ],
    delivery: {
      full_name: "Hauwa Ibrahim",
      phone_number: "+234 902 334 9981",
      line: "PLOT 14 Asokoro",
      city: "Abuja",
      state: "FCT",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2816",
    order_number: "#ORD-2816",
    customer_name: "Esther Adeola",
    customer_whatsapp: "+234 814 778 2210",
    status: "delivered",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 11000,
    created_at: ago(8, "d"),
    items: [item("g20", "11", "Bubu Dress", "BD-010", "#2A6E54", "BD", 11000, 1)],
    delivery: {
      full_name: "Esther Adeola",
      phone_number: "+234 814 778 2210",
      line: "31 Ring Road",
      city: "Ibadan",
      state: "Oyo",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2815",
    order_number: "#ORD-2815",
    customer_name: "David Adebayo",
    customer_whatsapp: "+234 803 663 8870",
    status: "pending",
    payment_status: "pending",
    total_amount: 150000,
    created_at: ago(5, "h"),
    items: [
      item("g21", "26", "Bridal Lace", "BL-025", "#1F4D7A", "BL", 75000, 2),
    ],
    delivery: {
      full_name: "David Adebayo",
      phone_number: "+234 803 663 8870",
      line: "PLOT 1 Ikoyi Crescent",
      city: "Ikoyi",
      state: "Lagos",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2814",
    order_number: "#ORD-2814",
    customer_name: "Grace Olatunji",
    customer_whatsapp: "+234 906 445 7790",
    status: "cancelled",
    payment_status: "failed",
    total_amount: 22000,
    created_at: ago(9, "d"),
    items: [item("g22", "38", "Coral Beads Set", "CB-037", "#1F4D7A", "CB", 22000, 1)],
    delivery: {
      full_name: "Grace Olatunji",
      phone_number: "+234 906 445 7790",
      line: "44 Mile 1",
      city: "Diobu",
      state: "Rivers",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2813",
    order_number: "#ORD-2813",
    customer_name: "Ahmed Musa",
    customer_whatsapp: "+234 815 998 1145",
    status: "paid",
    payment_status: "completed",
    payment_method: "Paystack",
    total_amount: 18500,
    created_at: ago(15, "h"),
    items: [item("g23", "21", "Leather Sandal", "LS-020", "#5C3B7E", "LS", 18500, 1)],
    delivery: {
      full_name: "Ahmed Musa",
      phone_number: "+234 815 998 1145",
      line: "27 Race Course",
      city: "Kano",
      state: "Kano",
      country: "Nigeria",
    },
  },
  {
    id: "ord-2812",
    order_number: "#ORD-2812",
    customer_name: "Stella Eke",
    customer_whatsapp: "+234 706 552 3387",
    status: "pending",
    payment_status: "pending",
    total_amount: 9000,
    created_at: ago(2, "h"),
    items: [item("g24", "36", "Stretch Ankara Pants", "SP-035", "#3A3D44", "SP", 9000, 1)],
    delivery: {
      full_name: "Stella Eke",
      phone_number: "+234 706 552 3387",
      line: "12 Niger Bridge Head",
      city: "Onitsha",
      state: "Anambra",
      country: "Nigeria",
    },
  },
]
