import type {
  OrderItemResponse,
  OrderResponse,
  OrderStatus,
  PaymentStatus,
} from "@/lib/api/types"

export type Order = OrderResponse
export type OrderItem = OrderItemResponse
export type { OrderStatus, PaymentStatus }

/** Helper to render an ISO date relative to "now" at module load. */
const ago = (amount: number, unit: "m" | "h" | "d"): string => {
  const ms =
    unit === "m"
      ? amount * 60_000
      : unit === "h"
        ? amount * 3_600_000
        : amount * 86_400_000
  return new Date(Date.now() - ms).toISOString()
}

/** Derive a stable mock customer_id from a customer name. */
const custId = (name: string): string =>
  `cust-${name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")}`

/** Item factory — keeps per-row construction compact. */
const item = (
  id: string,
  order_id: string,
  product_id: string,
  product_name: string,
  product_sku: string,
  unit_price: number,
  quantity = 1,
): OrderItemResponse => ({
  id,
  order_id,
  product_id,
  product_name,
  product_sku,
  quantity,
  unit_price,
  subtotal: unit_price * quantity,
})

export const MOCK_ORDERS: OrderResponse[] = [
  // -------- named entries from the spec --------
  {
    id: "ord-2841",
    order_number: "#ORD-2841",
    customer_id: custId("Emperor Eze"),
    customer_name: "Emperor",
    customer_whatsapp_number: "+234 803 124 8841",
    status: "pending",
    payment_status: "pending",
    total_amount: 43500,
    address_full_name: "Emperor Eze",
    address_phone_number: "+234 803 124 8841",
    address_line: "14 Wole Soyinka Street",
    address_city: "Yaba",
    address_state: "Lagos",
    address_country: "Nigeria",
    address_landmark: "Beside Eko Hospital",
    created_at: ago(2, "h"),
    updated_at: ago(2, "h"),
  },
  {
    id: "ord-2840",
    order_number: "#ORD-2840",
    customer_id: custId("Ada Obi"),
    customer_name: "Ada Obi",
    customer_whatsapp_number: "+234 802 551 0922",
    status: "paid",
    payment_status: "completed",
    total_amount: 18000,
    address_full_name: "Ada Obi",
    address_phone_number: "+234 802 551 0922",
    address_line: "22 Adeniyi Jones Avenue",
    address_city: "Ikeja",
    address_state: "Lagos",
    address_country: "Nigeria",
    created_at: ago(4, "h"),
    updated_at: ago(4, "h"),
  },
  {
    id: "ord-2839",
    order_number: "#ORD-2839",
    customer_id: custId("Tunde Bello"),
    customer_name: "Tunde B.",
    customer_whatsapp_number: "+234 814 220 4571",
    status: "shipped",
    payment_status: "completed",
    total_amount: 96200,
    address_full_name: "Tunde Bello",
    address_phone_number: "+234 814 220 4571",
    address_line: "9 Allen Avenue",
    address_city: "Ikeja",
    address_state: "Lagos",
    address_country: "Nigeria",
    address_landmark: "Opposite Computer Village",
    created_at: ago(1, "d"),
    updated_at: ago(1, "d"),
  },
  {
    id: "ord-2838",
    order_number: "#ORD-2838",
    customer_id: custId("Chioma Nwosu"),
    customer_name: "Chioma N.",
    customer_whatsapp_number: "+234 706 992 1140",
    status: "delivered",
    payment_status: "completed",
    total_amount: 12750,
    address_full_name: "Chioma Nwosu",
    address_phone_number: "+234 706 992 1140",
    address_line: "5b Bourdillon Road",
    address_city: "Ikoyi",
    address_state: "Lagos",
    address_country: "Nigeria",
    created_at: ago(2, "d"),
    updated_at: ago(2, "d"),
  },
  {
    id: "ord-2837",
    order_number: "#ORD-2837",
    customer_id: custId("Musa Khalid"),
    customer_name: "Musa K.",
    customer_whatsapp_number: "+234 815 008 3306",
    status: "cancelled",
    payment_status: "failed",
    total_amount: 7400,
    address_full_name: "Musa Khalid",
    address_phone_number: "+234 815 008 3306",
    address_line: "PLOT 12 Wuse Zone 4",
    address_city: "Abuja",
    address_state: "FCT",
    address_country: "Nigeria",
    created_at: ago(3, "d"),
    updated_at: ago(3, "d"),
  },
  {
    id: "ord-2836",
    order_number: "#ORD-2836",
    customer_id: custId("Ifeoma Okafor"),
    customer_name: "Ifeoma O.",
    customer_whatsapp_number: "+234 803 478 1290",
    status: "delivered",
    payment_status: "completed",
    total_amount: 25000,
    address_full_name: "Ifeoma Okafor",
    address_phone_number: "+234 803 478 1290",
    address_line: "47 Olu Obasanjo Avenue",
    address_city: "Port Harcourt",
    address_state: "Rivers",
    address_country: "Nigeria",
    created_at: ago(4, "d"),
    updated_at: ago(4, "d"),
  },

  // -------- generated entries (24) --------
  {
    id: "ord-2835",
    order_number: "#ORD-2835",
    customer_id: custId("Adaobi Eze"),
    customer_name: "Adaobi Eze",
    customer_whatsapp_number: "+234 803 211 4456",
    status: "paid",
    payment_status: "completed",
    total_amount: 15500,
    address_full_name: "Adaobi Eze",
    address_phone_number: "+234 803 211 4456",
    address_line: "12 Awolowo Road",
    address_city: "Ikoyi",
    address_state: "Lagos",
    address_country: "Nigeria",
    created_at: ago(5, "h"),
    updated_at: ago(5, "h"),
  },
  {
    id: "ord-2834",
    order_number: "#ORD-2834",
    customer_id: custId("Tunde Adeyemi"),
    customer_name: "Tunde Adeyemi",
    customer_whatsapp_number: "+234 814 776 2210",
    status: "pending",
    payment_status: "pending",
    total_amount: 8900,
    address_full_name: "Tunde Adeyemi",
    address_phone_number: "+234 814 776 2210",
    address_line: "23 Opebi Road",
    address_city: "Ikeja",
    address_state: "Lagos",
    address_country: "Nigeria",
    created_at: ago(8, "h"),
    updated_at: ago(8, "h"),
  },
  {
    id: "ord-2833",
    order_number: "#ORD-2833",
    customer_id: custId("Funke Okonkwo"),
    customer_name: "Funke Okonkwo",
    customer_whatsapp_number: "+234 706 433 1290",
    status: "paid",
    payment_status: "completed",
    total_amount: 35000,
    address_full_name: "Funke Okonkwo",
    address_phone_number: "+234 706 433 1290",
    address_line: "8 Lekki Phase 1",
    address_city: "Lekki",
    address_state: "Lagos",
    address_country: "Nigeria",
    created_at: ago(12, "h"),
    updated_at: ago(12, "h"),
  },
  {
    id: "ord-2832",
    order_number: "#ORD-2832",
    customer_id: custId("Chidi Nwankwo"),
    customer_name: "Chidi Nwankwo",
    customer_whatsapp_number: "+234 815 990 4521",
    status: "shipped",
    payment_status: "completed",
    total_amount: 42500,
    address_full_name: "Chidi Nwankwo",
    address_phone_number: "+234 815 990 4521",
    address_line: "44 Aba Road",
    address_city: "Port Harcourt",
    address_state: "Rivers",
    address_country: "Nigeria",
    created_at: ago(2, "d"),
    updated_at: ago(2, "d"),
  },
  {
    id: "ord-2831",
    order_number: "#ORD-2831",
    customer_id: custId("Bisi Ade"),
    customer_name: "Bisi Ade",
    customer_whatsapp_number: "+234 803 887 3344",
    status: "delivered",
    payment_status: "completed",
    total_amount: 9500,
    address_full_name: "Bisi Ade",
    address_phone_number: "+234 803 887 3344",
    address_line: "10 Adeniran Ogunsanya St",
    address_city: "Surulere",
    address_state: "Lagos",
    address_country: "Nigeria",
    created_at: ago(5, "d"),
    updated_at: ago(5, "d"),
  },
  {
    id: "ord-2830",
    order_number: "#ORD-2830",
    customer_id: custId("Femi Bakare"),
    customer_name: "Femi Bakare",
    customer_whatsapp_number: "+234 906 122 7768",
    status: "pending",
    payment_status: "pending",
    total_amount: 12000,
    address_full_name: "Femi Bakare",
    address_phone_number: "+234 906 122 7768",
    address_line: "5 Independence Way",
    address_city: "Kaduna",
    address_state: "Kaduna",
    address_country: "Nigeria",
    created_at: ago(1, "h"),
    updated_at: ago(1, "h"),
  },
  {
    id: "ord-2829",
    order_number: "#ORD-2829",
    customer_id: custId("Yetunde Lawal"),
    customer_name: "Yetunde Lawal",
    customer_whatsapp_number: "+234 802 445 1190",
    status: "paid",
    payment_status: "completed",
    total_amount: 67500,
    address_full_name: "Yetunde Lawal",
    address_phone_number: "+234 802 445 1190",
    address_line: "PLOT 7 Maitama",
    address_city: "Abuja",
    address_state: "FCT",
    address_country: "Nigeria",
    created_at: ago(6, "h"),
    updated_at: ago(6, "h"),
  },
  {
    id: "ord-2828",
    order_number: "#ORD-2828",
    customer_id: custId("Kunle Ojo"),
    customer_name: "Kunle Ojo",
    customer_whatsapp_number: "+234 814 552 3387",
    status: "pending",
    payment_status: "pending",
    total_amount: 5500,
    address_full_name: "Kunle Ojo",
    address_phone_number: "+234 814 552 3387",
    address_line: "16 Ibadan Express",
    address_city: "Ibadan",
    address_state: "Oyo",
    address_country: "Nigeria",
    created_at: ago(3, "h"),
    updated_at: ago(3, "h"),
  },
  {
    id: "ord-2827",
    order_number: "#ORD-2827",
    customer_id: custId("Ngozi Akpan"),
    customer_name: "Ngozi Akpan",
    customer_whatsapp_number: "+234 706 334 6612",
    status: "cancelled",
    payment_status: "failed",
    total_amount: 18000,
    address_full_name: "Ngozi Akpan",
    address_phone_number: "+234 706 334 6612",
    address_line: "30 New Haven",
    address_city: "Enugu",
    address_state: "Enugu",
    address_country: "Nigeria",
    created_at: ago(6, "d"),
    updated_at: ago(6, "d"),
  },
  {
    id: "ord-2826",
    order_number: "#ORD-2826",
    customer_id: custId("Olumide Smith"),
    customer_name: "Olumide Smith",
    customer_whatsapp_number: "+234 803 991 4456",
    status: "shipped",
    payment_status: "completed",
    total_amount: 108000,
    address_full_name: "Olumide Smith",
    address_phone_number: "+234 803 991 4456",
    address_line: "21 Banana Island",
    address_city: "Ikoyi",
    address_state: "Lagos",
    address_country: "Nigeria",
    address_landmark: "Gate 3",
    created_at: ago(3, "d"),
    updated_at: ago(3, "d"),
  },
  {
    id: "ord-2825",
    order_number: "#ORD-2825",
    customer_id: custId("Tope Akin"),
    customer_name: "Tope Akin",
    customer_whatsapp_number: "+234 815 663 7790",
    status: "paid",
    payment_status: "completed",
    total_amount: 25000,
    address_full_name: "Tope Akin",
    address_phone_number: "+234 815 663 7790",
    address_line: "4 University Road",
    address_city: "Akoka",
    address_state: "Lagos",
    address_country: "Nigeria",
    created_at: ago(7, "h"),
    updated_at: ago(7, "h"),
  },
  {
    id: "ord-2824",
    order_number: "#ORD-2824",
    customer_id: custId("Sade Davis"),
    customer_name: "Sade Davis",
    customer_whatsapp_number: "+234 902 887 4422",
    status: "pending",
    payment_status: "pending",
    total_amount: 4500,
    address_full_name: "Sade Davis",
    address_phone_number: "+234 902 887 4422",
    address_line: "7 Bode Thomas",
    address_city: "Surulere",
    address_state: "Lagos",
    address_country: "Nigeria",
    created_at: ago(30, "m"),
    updated_at: ago(30, "m"),
  },
  {
    id: "ord-2823",
    order_number: "#ORD-2823",
    customer_id: custId("Bayo Falade"),
    customer_name: "Bayo Falade",
    customer_whatsapp_number: "+234 814 998 1123",
    status: "delivered",
    payment_status: "completed",
    total_amount: 52000,
    address_full_name: "Bayo Falade",
    address_phone_number: "+234 814 998 1123",
    address_line: "5 Mokola",
    address_city: "Ibadan",
    address_state: "Oyo",
    address_country: "Nigeria",
    created_at: ago(7, "d"),
    updated_at: ago(7, "d"),
  },
  {
    id: "ord-2822",
    order_number: "#ORD-2822",
    customer_id: custId("Ifeanyi Obi"),
    customer_name: "Ifeanyi Obi",
    customer_whatsapp_number: "+234 803 446 8890",
    status: "paid",
    payment_status: "completed",
    total_amount: 19000,
    address_full_name: "Ifeanyi Obi",
    address_phone_number: "+234 803 446 8890",
    address_line: "12 Independence Layout",
    address_city: "Enugu",
    address_state: "Enugu",
    address_country: "Nigeria",
    created_at: ago(9, "h"),
    updated_at: ago(9, "h"),
  },
  {
    id: "ord-2821",
    order_number: "#ORD-2821",
    customer_id: custId("Halima Aliyu"),
    customer_name: "Halima Aliyu",
    customer_whatsapp_number: "+234 906 552 3344",
    status: "pending",
    payment_status: "pending",
    total_amount: 8500,
    address_full_name: "Halima Aliyu",
    address_phone_number: "+234 906 552 3344",
    address_line: "PLOT 22 Garki II",
    address_city: "Abuja",
    address_state: "FCT",
    address_country: "Nigeria",
    created_at: ago(14, "h"),
    updated_at: ago(14, "h"),
  },
  {
    id: "ord-2820",
    order_number: "#ORD-2820",
    customer_id: custId("Mary James"),
    customer_name: "Mary James",
    customer_whatsapp_number: "+234 815 117 4490",
    status: "shipped",
    payment_status: "completed",
    total_amount: 31500,
    address_full_name: "Mary James",
    address_phone_number: "+234 815 117 4490",
    address_line: "9 Eastern Bypass",
    address_city: "Owerri",
    address_state: "Imo",
    address_country: "Nigeria",
    created_at: ago(4, "d"),
    updated_at: ago(4, "d"),
  },
  {
    id: "ord-2819",
    order_number: "#ORD-2819",
    customer_id: custId("Peter Okeke"),
    customer_name: "Peter Okeke",
    customer_whatsapp_number: "+234 706 998 5562",
    status: "paid",
    payment_status: "completed",
    total_amount: 14500,
    address_full_name: "Peter Okeke",
    address_phone_number: "+234 706 998 5562",
    address_line: "1 Trans Amadi",
    address_city: "Port Harcourt",
    address_state: "Rivers",
    address_country: "Nigeria",
    created_at: ago(11, "h"),
    updated_at: ago(11, "h"),
  },
  {
    id: "ord-2818",
    order_number: "#ORD-2818",
    customer_id: custId("John Bello"),
    customer_name: "John Bello",
    customer_whatsapp_number: "+234 803 223 7780",
    status: "pending",
    payment_status: "pending",
    total_amount: 7800,
    address_full_name: "John Bello",
    address_phone_number: "+234 803 223 7780",
    address_line: "16 Awolowo Way",
    address_city: "Ikeja",
    address_state: "Lagos",
    address_country: "Nigeria",
    created_at: ago(20, "h"),
    updated_at: ago(20, "h"),
  },
  {
    id: "ord-2817",
    order_number: "#ORD-2817",
    customer_id: custId("Hauwa Ibrahim"),
    customer_name: "Hauwa Ibrahim",
    customer_whatsapp_number: "+234 902 334 9981",
    status: "paid",
    payment_status: "completed",
    total_amount: 95000,
    address_full_name: "Hauwa Ibrahim",
    address_phone_number: "+234 902 334 9981",
    address_line: "PLOT 14 Asokoro",
    address_city: "Abuja",
    address_state: "FCT",
    address_country: "Nigeria",
    created_at: ago(13, "h"),
    updated_at: ago(13, "h"),
  },
  {
    id: "ord-2816",
    order_number: "#ORD-2816",
    customer_id: custId("Esther Adeola"),
    customer_name: "Esther Adeola",
    customer_whatsapp_number: "+234 814 778 2210",
    status: "delivered",
    payment_status: "completed",
    total_amount: 11000,
    address_full_name: "Esther Adeola",
    address_phone_number: "+234 814 778 2210",
    address_line: "31 Ring Road",
    address_city: "Ibadan",
    address_state: "Oyo",
    address_country: "Nigeria",
    created_at: ago(8, "d"),
    updated_at: ago(8, "d"),
  },
  {
    id: "ord-2815",
    order_number: "#ORD-2815",
    customer_id: custId("David Adebayo"),
    customer_name: "David Adebayo",
    customer_whatsapp_number: "+234 803 663 8870",
    status: "pending",
    payment_status: "pending",
    total_amount: 150000,
    address_full_name: "David Adebayo",
    address_phone_number: "+234 803 663 8870",
    address_line: "PLOT 1 Ikoyi Crescent",
    address_city: "Ikoyi",
    address_state: "Lagos",
    address_country: "Nigeria",
    created_at: ago(5, "h"),
    updated_at: ago(5, "h"),
  },
  {
    id: "ord-2814",
    order_number: "#ORD-2814",
    customer_id: custId("Grace Olatunji"),
    customer_name: "Grace Olatunji",
    customer_whatsapp_number: "+234 906 445 7790",
    status: "cancelled",
    payment_status: "failed",
    total_amount: 22000,
    address_full_name: "Grace Olatunji",
    address_phone_number: "+234 906 445 7790",
    address_line: "44 Mile 1",
    address_city: "Diobu",
    address_state: "Rivers",
    address_country: "Nigeria",
    created_at: ago(9, "d"),
    updated_at: ago(9, "d"),
  },
  {
    id: "ord-2813",
    order_number: "#ORD-2813",
    customer_id: custId("Ahmed Musa"),
    customer_name: "Ahmed Musa",
    customer_whatsapp_number: "+234 815 998 1145",
    status: "paid",
    payment_status: "completed",
    total_amount: 18500,
    address_full_name: "Ahmed Musa",
    address_phone_number: "+234 815 998 1145",
    address_line: "27 Race Course",
    address_city: "Kano",
    address_state: "Kano",
    address_country: "Nigeria",
    created_at: ago(15, "h"),
    updated_at: ago(15, "h"),
  },
  {
    id: "ord-2812",
    order_number: "#ORD-2812",
    customer_id: custId("Stella Eke"),
    customer_name: "Stella Eke",
    customer_whatsapp_number: "+234 706 552 3387",
    status: "pending",
    payment_status: "pending",
    total_amount: 9000,
    address_full_name: "Stella Eke",
    address_phone_number: "+234 706 552 3387",
    address_line: "12 Niger Bridge Head",
    address_city: "Onitsha",
    address_state: "Anambra",
    address_country: "Nigeria",
    created_at: ago(2, "h"),
    updated_at: ago(2, "h"),
  },
]

/**
 * Items split out from orders. The API delivers items via a separate endpoint
 * (GET /orders/{id}/items), so this mirrors that shape — look up by order id
 * to render the items section.
 */
export const MOCK_ORDER_ITEMS_BY_ORDER: Record<string, OrderItemResponse[]> = {
  "ord-2841": [
    item("i1", "ord-2841", "1", "Ankara Midi Dress", "AMD-001", 12500, 1),
    item("i2", "ord-2841", "4", "Agbada Set", "AS-004", 31000, 1),
  ],
  "ord-2840": [item("i3", "ord-2840", "2", "Senator Kaftan", "SK-002", 18000, 1)],
  "ord-2839": [
    item("i4", "ord-2839", "3", "Lace Gown", "LG-003", 25000, 2),
    item("i5", "ord-2839", "15", "Brocade Agbada", "BA-014", 46200, 1),
  ],
  "ord-2838": [
    item("i6", "ord-2838", "11", "Bubu Dress", "BD-010", 11000, 1),
    item("i7", "ord-2838", "5", "Gele Headwrap", "GH-005", 1750, 1),
  ],
  "ord-2837": [item("i8", "ord-2837", "19", "Native Cap", "NC-018", 7400, 1)],
  "ord-2836": [item("i9", "ord-2836", "3", "Lace Gown", "LG-003", 25000, 1)],
  "ord-2835": [item("g1", "ord-2835", "8", "Kente Wrapper", "KW-007", 15500, 1)],
  "ord-2834": [
    item("g2", "ord-2834", "23", "Girls Ankara Dress", "GA-022", 8500, 1),
    item("g2b", "ord-2834", "5", "Gele Headwrap", "GH-005", 400, 1),
  ],
  "ord-2833": [item("g3", "ord-2833", "33", "Sequin Evening Dress", "SQ-032", 35000, 1)],
  "ord-2832": [
    item("g4", "ord-2832", "9", "Velvet Sequin Gown", "VG-008", 38000, 1),
    item("g4b", "ord-2832", "5", "Gele Headwrap", "GH-005", 4500, 1),
  ],
  "ord-2831": [item("g5", "ord-2831", "7", "Adire Boubou", "AB-006", 9500, 1)],
  "ord-2830": [item("g6", "ord-2830", "24", "Plain Slim Pants", "PS-023", 12000, 1)],
  "ord-2829": [item("g7", "ord-2829", "26", "Bridal Lace", "BL-025", 67500, 1)],
  "ord-2828": [item("g8", "ord-2828", "10", "Aso Oke Cap", "AO-009", 5500, 1)],
  "ord-2827": [item("g9", "ord-2827", "18", "Iro and Buba Set", "IB-017", 18000, 1)],
  "ord-2826": [
    item("g10", "ord-2826", "15", "Brocade Agbada", "BA-014", 52000, 1),
    item("g10b", "ord-2826", "13", "Embellished Senator", "ES-012", 32000, 1),
    item("g10c", "ord-2826", "4", "Agbada Set", "AS-004", 24000, 1),
  ],
  "ord-2825": [item("g11", "ord-2825", "3", "Lace Gown", "LG-003", 25000, 1)],
  "ord-2824": [item("g12", "ord-2824", "5", "Gele Headwrap", "GH-005", 4500, 1)],
  "ord-2823": [item("g13", "ord-2823", "15", "Brocade Agbada", "BA-014", 52000, 1)],
  "ord-2822": [item("g14", "ord-2822", "22", "Boys Senator Set", "BS-021", 19000, 1)],
  "ord-2821": [item("g15", "ord-2821", "23", "Girls Ankara Dress", "GA-022", 8500, 1)],
  "ord-2820": [
    item("g16", "ord-2820", "14", "Lace Aso Ebi Dress", "LA-013", 28500, 1),
    item("g16b", "ord-2820", "5", "Gele Headwrap", "GH-005", 3000, 1),
  ],
  "ord-2819": [item("g17", "ord-2819", "17", "Print Maxi Dress", "PM-016", 14500, 1)],
  "ord-2818": [item("g18", "ord-2818", "20", "Beaded Necklace", "BN-019", 7800, 1)],
  "ord-2817": [
    item("g19", "ord-2817", "26", "Bridal Lace", "BL-025", 75000, 1),
    item("g19b", "ord-2817", "8", "Kente Wrapper", "KW-007", 20000, 1),
  ],
  "ord-2816": [item("g20", "ord-2816", "11", "Bubu Dress", "BD-010", 11000, 1)],
  "ord-2815": [item("g21", "ord-2815", "26", "Bridal Lace", "BL-025", 75000, 2)],
  "ord-2814": [item("g22", "ord-2814", "38", "Coral Beads Set", "CB-037", 22000, 1)],
  "ord-2813": [item("g23", "ord-2813", "21", "Leather Sandal", "LS-020", 18500, 1)],
  "ord-2812": [item("g24", "ord-2812", "36", "Stretch Ankara Pants", "SP-035", 9000, 1)],
}
